wibsonorg/buyer-sdk

buyer-signing-service/src/helpers/accounts.js
buyer-signing-service/src/routes/accounts.js

Expose root account information so that BAPI can manage to transfer WIB or ether to their children

Expose root account

---

buyer-api/src/routes/account.js

Update Buyer API to consolidate balances of root/children accounts

Update balance method

---

buyer-api/.env.example
buyer-api/config/index.js
buyer-api/package-lock.json
buyer-api/package.json
buyer-api/src/utils/logger.js

Enables certain logs (`crit`, `alert`, and `emerg`) to be logged to a slack channel.
No
Enhancement

Slack Notification logger

---

buyer-api/package.json
buyer-api/src/app.js
buyer-api/src/facades/createDataOrderFacade.js
buyer-api/src/facades/getBatchesFacade.js
buyer-api/src/facades/index.js
buyer-api/src/queues/createDataOrderQueue.js
buyer-api/src/routes/dataOrders/batches.js
buyer-api/src/routes/dataOrders/createDataOrder.js
buyer-api/src/routes/dataOrders/index.js
buyer-api/src/services/batchInfo.js

Batch queue + Consolidate responses

---

buyer-api/src/facades/getOrdersFacade.js
buyer-api/src/routes/dataOrders/createDataOrder.js
buyer-api/src/utils/wibson-lib/s3/index.js
buyer-app/buyer-app/src/state/entities/dataOrdersAddresses/sagas.js
buyer-signing-service/src/facades/sign/newOrderFacade.js

The `orderAddress` was renamed to `address` without taking into account the impact on the buyer app. This PR reverts it. @Meketh as the author.
No.
This is needed to make the buyer app work again.

Revert the renaming of orderAddress to address.

---

buyer-api/src/routes/account.js
buyer-api/src/utils/index.js
buyer-api/src/utils/wibson-lib/coin/index.js
buyer-api/test/facades/addNotariesToOrderFacadeSpec.js
buyer-api/test/facades/createDataOrderFacadeSpec.js
buyer-api/test/facades/transferFacadeSpec.js
buyer-api/test/routes/dataOrders/addNotariesToOrderSpec.js
buyer-api/test/routes/dataOrders/createDataOrderSpec.js
buyer-api/test/routes/health_spec.js
buyer-api/test/setup.js

Extract changes made in https://github.com/wibsonorg/buyer-sdk/pull/39 to the `toWib` function to another formatting helper and use it in the response of `GET /account`
Some tests where skipped to prioritize tests that are currently working

Fix Wibson Token formatting

---

buyer-api/src/facades/dataResponseFacade/addDataResponse.js
buyer-api/src/facades/getOrdersFacade.js
buyer-api/src/utils/wibson-lib/s3/index.js

S3 methods take order address as parameter.
No.
The current way is cumbersome and error prone.

S3 methods take order address as parameter

---

buyer-app/buyer-app/src/state/entities/dataOrdersByAddress/reducers.js

It removes the pending data orders from the data order list.
No
Pending data orders lacks of some data needed, like orderAddress

removed createDataOrderSucceed from dataOrderByAddress reducer

---

buyer-app/buyer-app/package.json
buyer-app/buyer-app/src/components/buyer/DataOrderCreate/DataOrderCreate.js

add select multiple for various notaries

---

buyer-api/src/facades/dataResponseFacade/addDataResponse.js
buyer-api/src/facades/dataResponseFacade/closeDataResponse.js
buyer-api/src/facades/helpers/getBuyerAccount.js

Fixes the buyData flow
So that a seller can sell his data in our platform

Fix buy data flow

---

buyer-api/src/routes/dataOrders/closeDataOrder.js
buyer-app/buyer-app/src/lib/protocol-helpers/data-orders.js

Change the /order/close endpoint to /order/end
No
As a possible fix on the unable to close orders bug

 /orders/{orderAddress}/close -> /orders/{orderAddress}/end

---

buyer-api/src/app.js
buyer-api/src/routes/dataResponses.js

It stops accepting offers from a banned list.
No
Nasty hack so we dont need to remove orders in order to create new ones for now

undead orders hack

---

buyer-api/package-lock.json
buyer-api/src/facades/helpers/index.js
buyer-api/src/facades/helpers/performTransaction.js
buyer-api/src/queues/index.js
buyer-api/src/queues/transactionQueue.js

Creates the transaction queue needed to process transaction sequentially.

Add TransactionQueue

---

buyer-api/src/facades/closeDataOrderFacade.js

Updates the Close DataOrder flow to use the transaction processing scheme.

Update Close DataOrder flow

---

buyer-api/src/facades/createDataOrderFacade.js
buyer-api/src/facades/getOrdersFacade.js

Fix address casing
Without this fix, notary tag in orders list is not shown on the Buyer APP

Downcase notaries address list in DataOrder detail

---

buyer-api/src/contractEventSubscribers/buyDataSubscriber.js
buyer-api/src/facades/helpers/performTransaction.js
buyer-api/src/queues/createQueue.js
buyer-api/src/queues/transactionQueue.js

Cleanup the log output so that it is easy to inspect what is happening to the transactions that are sent to the network.

Cleanup logs

---

buyer-api/src/routes/auth.js
buyer-app/buyer-app/src/components/buyer/Buyer.js
buyer-app/buyer-app/src/components/buyer/OpenDataOrders/OpenDataOrders.js
buyer-app/buyer-app/src/state/entities/account/sagas.js
buyer-app/buyer-app/src/state/entities/authentication/actions.js
buyer-app/buyer-app/src/state/entities/authentication/sagas.js

I could not reproduce the error of the N/A, in the balance display, but make some changes in the authentication, handle the logout in the updateAccount, if status 401. And when the logout button was pressed, the action was called and not the watch in the saga

Jc fix display balance and verify token

---

buyer-api/src/facades/closeBatchFacade.js
buyer-api/src/facades/closeDataOrderFacade.js
buyer-api/src/facades/getBatchesFacade.js
buyer-api/src/facades/helpers/index.js
buyer-api/src/facades/helpers/performTransaction.js

Adds some error handling when closing orders of a batch.
No.
In case that a close order transaction fails, we have to retry in a smart way (not retry if EVM error, retry if pending, etc).

Error handling in close queue

---

buyer-api/scripts/test.sh
buyer-api/test/setup.js
buyer-signing-service/src/server.js
buyer-signing-service/src/utils/writePid.js

Starts the signing service automatically and before the tests are run.

Add Signing Service initialization in test script

---

buyer-api/test/facades/addNotariesToOrderFacade.test.js
buyer-api/test/facades/closeDataOrderFacade.test.js
buyer-api/test/facades/dataResponseFacade/addDataResponse.test.js
buyer-api/test/facades/dataResponseFacade/closeDataResponse.test.js
buyer-api/test/facades/dataResponseFacade/increaseApproval.test.js
buyer-api/test/queues/transactionQueue.test.js

Adds some test files to be used with `ava`
No
Improve automatic testing in buyer-sdk

Adding test cases

---

buyer-api/scripts/test.sh
buyer-api/src/facades/dataResponseFacade/addDataResponse.js
buyer-api/test/facades/dataResponseFacade/addDataResponse.test.js
buyer-api/test/facades/dataResponseFacade/closeDataResponse.test.js
buyer-api/test/facades/dataResponseFacade/increaseApproval.test.js
buyer-api/test/setup.js

Adds data response related tests. 
No
To have a more robust sdk.

Data Response tests

---

buyer-api/package-lock.json
buyer-api/package.json
buyer-api/scripts/test.sh
buyer-api/src/facades/helpers/performTransaction.js
buyer-api/src/queues/transactionQueue.js
buyer-api/src/utils/logger.js
buyer-api/test/queues/transactionQueue.test.js
buyer-api/test/setup.js
buyer-api/test/support/FakeProvider.js
buyer-api/test/support/receiptFactory.js

Adds tests to the transactionQueue module.
* Logger configuration for test environment is out of scope, but it is handy when it comes to debugging your tests (it only logs to a file).
* Fix a bug regarding the mocking of `createLevelStore`: if no database name was supplied the mocked leveldb would fail in specific cases.

Test transactionQueue module

---

buyer-api/test/facades/dataResponseFacade/increaseApproval.test.js

Remove the dependency of a deployed `DataExchange` in `increaseApproval` test.
No
It was not working if DataExchange address was outdated

Using same logic as add/close data response

---

buyer-app/.gitignore
buyer-app/buyer-app/configuration/development.json.example

Ignores local config.
No.
This way we can use local IP, to test on real iOS devices.

ignore development json

---

buyer-app/buyer-app/src/components/buyer/DataOrderCreate/DataOrderCreate.js

Allows to select more than a single data connector on data order creation.
No
To add support for multiple data request.

add support for multiple data request

---

buyer-api/.env.example
buyer-api/config/index.js
buyer-api/src/queues/createQueue.js
buyer-api/src/utils/storage.js

Allows remote connection for redis and configures bull queues.
No.
- Bull queues were not using the configured redis.
- We need to connect to redis through URL to support remote connections.

Redis configuration for queues

---

buyer-api/src/contractEventSubscribers/buyDataSubscriber.js
buyer-api/src/facades/dataResponseFacade/closeDataResponse.js

Performs a check before trying to enqueue a closeDataResponse job

Check that the DataOrder's buyer is ourselves before trying to close a DataResponse

---

.travis.yml

Enables file glob in `.travis.yml`
Releases were failing in Travis CI

Add file_glob option to travis configuration

---

buyer-api/.env.example

Add info for debugging purposes in `.env.example`
No
Simplify first startup process

add detailed debug options on .env.example

---

buyer-api/src/blockchain/balance.js
buyer-api/src/utils/cache.js
buyer-api/src/utils/storage.js

Fix some bugs that made into develop
No

some fixes

---

buyer-api/config/index.js
buyer-api/src/queues/dataResponseQueue.js
buyer-api/test/queues/dataResponseQueue.test.js

Skips Batch Processing
.
v2 compliance

Skip Batch Processing

---

buyer-api/scripts/batch-data-responses.sh
buyer-api/src/routes/batchDataResponse.js

script that calls endpoint for batch data responses
.
force execution of batch data responses

Calls endpoint and uses standard simple authorization

---

buyer-api/src/routes/buyerInfos.js
buyer-api/src/routes/dataOrders/offchainData.js
buyer-api/src/services/buyerInfo.js

Add missing fields in DataOrder's offchain data response
Swagger documentation
Seller App won't work without these changes, since it crashes trying to fetch missing order fields.

Update DataOrder's offchain data representation

---

buyer-api/src/routes/buyerInfos.js

Update of docs.
No
Outdated docs

Terms is outside category now

---

buyer-api/src/utils/stores.js

Adds notary's endpoint
No
Seller needs this endpoint to send the data.

Add notary's data responses endpoint

---

buyer-api/src/services/notaryService.js
buyer-api/src/utils/stores.js

Fix the notarization request url
No
protocol v2

Fix the notarization request url

---

buyer-api/src/services/notaryService.js

`payData` was being packed as `0xff0400000NaN` since #175 
This PR fixes this issue.
Files, functions, or lines of code that are tricky and should be reviewed carefully.
Can't send RegisterPayment transaction

Fix sellerId packing

---

buyer-api/src/operations/addDataResponse.js
buyer-api/src/routes/dataOrders/addDataResponse.js
buyer-api/src/services/notaryService.js
buyer-api/test/operations/addDataResponse.mock.js
buyer-api/test/operations/addDataResponse.test.js

- Fetches the seller from `sellers` store instead of requiring it at the endpoint, since the seller would not send (or know) the BatPay ID.
- Fix `transferNotarizacionResult` typo
No.
`addDataResponse` was failing

Remove sellerId from swagger schema + typo

---

buyer-api/src/operations/createDataOrder.js
buyer-api/src/utils/storage.js
buyer-api/test/operations/createDataOrder.mock.js

Create data order throws if any notary doesn't exists.
No
Stop orders from been created with nonexistent notaries.

Check notaries existance on create data order

---

buyer-api/scripts/publish.sh
buyer-signing-service/scripts/publish.sh

Adds `scripts` folder to package and installs only production dependencies to both API and SS
No
Ease the deployment process

Fix publish script

---

buyer-api/scripts/batch-data-responses.sh
buyer-api/src/routes/batchDataResponse.js
buyer-api/src/routes/health.js
buyer-api/src/utils/routes.js

Remove hardcoded values from script that triggers DataResponse processing.
Out of scope changes: 
* Add `validateAuthorizationToken` middleware
* Update health response structure to align with the rest of health check responses
Ease the deployment process

Update script to process data responses batch

---

buyer-api/src/utils/stores.js

Fix: First created order was being ignored (id ==0). I'm using `typeof` to avoid falsy values.
No.
Include `dxId == 0`

FIX: Store dxId == 0

---

buyer-signing-service/src/utils/wibson-lib/package.json

Removes a package json file that is mixed under the source folder. Probably a left over
Just a general look at it will do it.
It may cause issues with npm commands ran under those folders path branches.

Removes unnecessary package json

---

buyer-api/src/operations/addDataResponse.js
buyer-api/src/routes/dataOrders/addDataResponse.js
buyer-api/src/routes/dataOrders/closeDataOrder.js
buyer-api/test/operations/addDataResponse.test.js

Return 410 if the offer is closed.
No
Handle data responses for closed offers

handling status for closed offer

---

buyer-api/package-lock.json
buyer-api/package.json
buyer-api/src/utils/logger.js
buyer-signing-service/package-lock.json
buyer-signing-service/package.json
buyer-signing-service/src/utils/logger.js

Bumps version
No
Release of v2

Bump release version

---

buyer-signing-service/package.json

Briefly describe what this PR is about.
Files, functions, or lines of code that are tricky and should be reviewed carefully.
Reference issues in case this is a bugfix. Explain the rationale if it's a feature/enhancement.

web3-eth-abi caret removed, version bumped

---

buyer-app/base-app/src/state/ontologies/selectors.js
buyer-app/buyer-app/src/components/buyer/DataOrderCreate/DataOrderCreate.js
buyer-app/buyer-app/src/lib/protocol-helpers/data-orders.js
buyer-app/buyer-app/src/state/entities/account/sagas.js
buyer-app/buyer-app/src/state/entities/createDataOrder/sagas.js
buyer-app/buyer-app/src/state/entities/notaries/helpers.js

Update create offer

---

buyer-api/package-lock.json
buyer-api/package.json
buyer-app/.gitignore
buyer-app/base-app/package-lock.json
buyer-app/base-app/package.json
buyer-app/buyer-app/package-lock.json
buyer-app/buyer-app/package.json
buyer-app/package-lock.json

Bumps versions
NA
Testing on staging

Bump versions for api and app

---

buyer-api/src/blockchain/balance.js
buyer-api/src/operations/closeDataOrder.js
buyer-app/buyer-app/src/components/buyer/BalancePanel/BalancePanel.js
buyer-app/buyer-app/src/components/buyer/ListDataOrders/ListDataOrders.js
buyer-app/buyer-app/src/state/entities/closeDataOrder/sagas.js
buyer-app/buyer-app/src/state/entities/dataOrdersByAddress/reducers.js

Show closing status in order list when pressing on close button
No

Show closing status

---

buyer-app/base-app/src/components/Toast/Toast.css
buyer-app/buyer-app/src/state/entities/createDataOrder/sagas.js

Update "Notaries will be notified" pop up notification by “Order is being created”
No

Update pop up notification

---

buyer-api/package.json
buyer-api/src/console.js
buyer-api/src/utils/wibson-lib/index.js
buyer-api/src/utils/wibson-lib/loadEnv.js

Adds REPL console for importing and testing with the console (e.g.: querying stores)
No (it's the same as WAPI)
Test with console

REPL console

---

buyer-api/src/routes/dataOrders/createDataOrder.js
buyer-app/buyer-app/src/lib/protocol-helpers/data-orders.js

Fixes order creation
No
Create orders

Fix order creation

---

buyer-app/base-app/src/state/ontologies/selectors.js

Remove the unused audience filters
(Yep, just Country)
No
Avoid using useless audience filters

WIB-863/Remove unused audience selectors

---

buyer-api/.env.example
buyer-api/config/index.js
buyer-api/src/operations/getOrderData.js

Uses the uuid instead of dxid to get the raw data.
No.
Now data is stored by uuid instead of dxid.

Get data by order uuid instead of dxid

---

buyer-api/.env.example
buyer-api/config/index.js
buyer-api/src/app.js

Increases the body size that express can handle.
No.
To fix payments.

Fix register payment flow

---

buyer-api/package.json
buyer-api/src/migrations/batpay-balance.js
buyer-api/src/utils/storage.js
buyer-api/src/utils/stores.js

Adds a script to clear batpay related stores.
No
To migrate account states to one BatPay ID.

Batpay migration

---

buyer-api/package-lock.json
buyer-api/package.json
buyer-signing-service/package-lock.json
buyer-signing-service/package.json

Release v2.0.5

---

buyer-api/package-lock.json
buyer-api/package.json
buyer-api/src/migrations/batpay-balance.js
buyer-app/buyer-app/package-lock.json
buyer-app/buyer-app/package.json
buyer-signing-service/package-lock.json
buyer-signing-service/package.json

Fix migration script and bump version to v2.0.6
No

Fix migration script and bump version to v2.0.6

---

buyer-api/.env.example
buyer-api/config/index.js
buyer-api/package-lock.json
buyer-api/package.json
buyer-api/src/app.js
buyer-api/src/console.js
buyer-api/src/queues/dataResponseQueue.js
buyer-api/src/queues/notarizationQueue.js
buyer-api/src/server.js
buyer-api/src/utils/logger.js
buyer-api/src/utils/routes.js
buyer-signing-service/package-lock.json
buyer-signing-service/package.json

`swagger-tools` was parsing the request body because it ran before our `body-parser` middleware definition. With the changes in this PR it is not going to happen anymore.
* Slack transport for critical errors
* Updated `babel` dependency that was causing a warning
No
Use our configured `body-parser` instead of using the one provided by `swagger-tools`

Fix body-parser placement

---

README.md
buyer-api/package-lock.json
buyer-api/package.json
buyer-api/src/tasks/index.js
buyer-api/src/tasks/inspect-notarizations.js
buyer-api/src/tasks/locked-payments.js
buyer-api/src/tasks/migrations/batpay-balance.js
buyer-api/src/utils/logger.js
buyer-api/src/utils/storage.js

Tasks can be executed by running the following commands
```
$ npm run task:dev                     # displays available tasks in src directory
$ npm run task:dev -- <task-name>      # executes <task-name> from src directory
```
```
$ npm run task                         # displays available tasks in dist directory
$ npm run task -- <task-name>          # executes <task-name> from dist directory
```
It supports subdirectories, in which case the command will be:
```
$ npm run task -- <subdirectory>:<file-name-without-.js>
```
Example:
```
$ npm run task -- migrations:batpay-balance
```
In order to define a new task to be run by command line, a JS file should be created under the `src/tasks` directory.
It can be placed under a subdirectory like `src/tasks/migrations`.
Last but not least, the …

Executable tasks by command line

---

buyer-api/src/services/signingService.js

Fixes POST requests made to the signing service.
No.
Prod bug.

Signing Service post requests fixed
